name: Deploy to Google Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: mytutor-new

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCLOUD_SSH_KEY }}" > ~/.ssh/gcloud_ssh_key
          chmod 600 ~/.ssh/gcloud_ssh_key
          ssh-keyscan -H 34.100.233.69 >> ~/.ssh/known_hosts

      - name: Deploy FastAPI Application to Google Compute Engine
        run: |
          cd ~/edutor-ai
          git fetch --all
          git reset --hard origin/main
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          uvicorn main:app --host 0.0.0.0 --port 8001 --reload
          EOF
