name: Deploy to Google Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: mytutor-new

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GCLOUD_SSH_KEY }}" > ~/.ssh/gcloud_ssh_key
          chmod 600 ~/.ssh/gcloud_ssh_key
          ssh-keyscan -H 34.100.233.69 >> ~/.ssh/known_hosts

      - name: Debug Instance
        run: |
          ssh -i ~/.ssh/gcloud_ssh_key main.jaydipsinh@34.100.233.69 << 'EOF'
          echo "Current Directory:"
          pwd
          echo "Contents of Root Directory:"
          ls -la /root/
          echo "Contents of Home Directory:"
          ls -la /home/main.jaydipsinh/
          echo "Searching for edutor-ai folder:"
          find / -type d -name "edutor-ai" 2>/dev/null
          EOF
